[package]
name = "yaserde"
version = "0.8.0"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]
description = "Serialization and deserialization library"
keywords = ["Serialization", "Deserialization", "XML"]
license = "MIT"
repository = "https://github.com/media-io/yaserde"
homepage = "https://github.com/media-io/yaserde"
documentation = "https://docs.rs/yaserde"
readme = "../README.md"
edition = "2018"

[dependencies]

yaserde_derive = { version = "0.8", path = "../yaserde_derive", optional = true }
xml-rs = {git = "https://github.com/holg/xml-rs/", branch="text_patches"}
log = "0.4"


[dev-dependencies]
env_logger = "0.9.0"
yaserde_derive = { version = "0.8", path = "../yaserde_derive" }

[badges]
travis-ci = { repository = "media-io/yaserde" }
